### ISSUE TITLE
Swift 2 Compilation error

### ISSUE THREAD

**Issue by hardikdevios** [cemolcay/CEMKit-Swift#6]
This code is not optimized/supported with Swift 2 .. any chance to upgrade the Code ? thank you

**Comment by cemolcay** [comment]
Yes right, i will update it as soon as possible.

**Comment by hardikdevios** [comment]
@cemolcay great work buddy thanks for the support, Your Lib has been part of my every project

**Comment by hardikdevios** [comment]
Any chance for updates?

**Comment by hardikdevios** [comment]
Link #7
